services:
  back:
    image: node:20-alpine
    user: 1000:1000
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run start:dev

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data

volumes:
  mongo_data: